name: varsity_app
description: Mobile App to enhance financial literacy for Varsity Hackathon 2024
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
#  equatable:
  shared_preferences:
  swipe_cards: ^2.0.0+1
  sizer:
  csv: ^6.0.0
  animated_text_kit: ^4.2.2
  confetti: ^0.7.0
  draggable_home: ^1.0.5
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/
    - assets/data/
#    - assets/sounds/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/Proxima_Nova_Black.otf
          weight: 900
        - asset: fonts/Proxima_Nova_Extrabold.otf
          weight: 800
        - asset: fonts/Proxima_Nova_Regular.otf
          weight: 300
        - asset: fonts/Proxima_Nova_Thin.otf